In [10]:
import torchvision.datasets as dset
import torchvision.transforms as transforms
import numpy as np

In [11]:
data = dset.CocoCaptions(root = './val2014/val2014/',
                        annFile = './annotations_trainval2014/annotations/captions_val2014.json',
                        transform=transforms.ToTensor())

loading annotations into memory...
Done (t=0.76s)
creating index...
index created!


In [23]:
word_set = set()
word_set.add('unk_word')
for i in np.arange(0, int(len(data)/2)) :
    img, captions = data[i]
    for caption in captions:
        [word_set.add(word) for word in caption.replace(".","").lower().split()]
    
    if (i%1000 == 0):
        print("DOne 100")
print(len(word_set))
srted_word_set = sorted(word_set)

word_to_indx_dict = {srted_word_set[i]:i for i in np.arange(0, len(srted_word_set))}
indx_to_word_dict = {i:srted_word_set[i] for i in np.arange(0, len(srted_word_set))}

DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
DOne 100
15565


In [9]:
char_set = set()
word_set = set()
for i in np.arange(0, trainY.shape[0]):
    [char_set.add(c) for c in trainY[i]]
    [word_set.add(word) for word in trainY[i].split(' ')]
char_set.add('unk_char')
char_set.add('sos')
char_set.add('eos')
srted_char_set = sorted(char_set)
word_set.add('unk_word')
word_set.add('sos')
word_set.add('eos')
srted_word_set = sorted(word_set)
char_to_indx_dict = {srted_char_set[i]:i for i in np.arange(0, len(srted_char_set))}
indx_to_char_dict = {i:srted_char_set[i] for i in np.arange(0, len(srted_char_set))}

word_to_indx_dict = {srted_word_set[i]:i for i in np.arange(0, len(srted_word_set))}
indx_to_word_dict = {i:srted_word_set[i] for i in np.arange(0, len(srted_word_set))}


trainY_proc_data_c = []
trainY_proc_data_w = []
for i in np.arange(0, trainY.shape[0]):
    curr_numpy_c = [char_to_indx_dict[c] for c in trainY[i]]
    curr_numpy_w = [word_to_indx_dict[word] for word in trainY[i].split(' ')]
    trainY_proc_data_c.append(np.array( [char_to_indx_dict['sos']] + curr_numpy_c + [char_to_indx_dict['eos']]))
    trainY_proc_data_w.append(np.array([word_to_indx_dict['sos']]+ curr_numpy_w +[word_to_indx_dict['eos']]))
print(type(np.array(trainY_proc_data_c)))
print(type(np.array(trainY_proc_data_w)))

np.save('trainY_proc_data_c.npy', trainY_proc_data_c)
np.save('trainY_proc_data_w.npy', trainY_proc_data_w)


    replace(".","").lower().split()


img, captions = cap[40503]
len(cap[40503])
print(captions)

['a man in glasses is holding a wine glass', 'A man holds a glass in aroom with many other people', 'A man holds a glass as others mill around behind him. ', 'A group of people standing around in a room.', 'A man holding a glass speaking to someone']


In [36]:
trainY_proc_data_w = []
for i in np.arange(0, int(len(data)/2)):
    img, captions = data[i]
    curr_image_captions = []
    for caption in captions:
        caps_ind = [word_to_indx_dict[word] for word in caption.replace(".","").lower().split()]
        curr_image_captions.append(np.array(caps_ind))
    trainY_proc_data_w.append(np.array(curr_image_captions))
print(trainY_proc_data_w[1000])

[array([  393, 13497, 15318,   393,  6767,  5905, 14711,   720,  4998,
        5382,  3119,  9341,  9125,  7144])
 array([  393, 10181,  6919,   393, 14711, 12235,   986, 13774,  4734,
        9125,   393, 13497])
 array([  393, 14711, 15318,  5382,  6919,  7144, 15318,  7911, 13021,
       12240,  9199,   393, 13497, 15318,  2357])
 array([ 5382,  6919,   393,  2908, 14711, 12240,  9199,   393, 13497])
 array([  393,  7582,  2602, 13769,  7130, 12240,  9199, 13774,  4602,
        9125,   393,  4125, 13497])]


In [37]:
np.save('trainX.npy', trainY_proc_data_w)